/**
 * Tripo Model Manager
 *
 * Handles loading, caching, and managing 3D models generated by Tripo AI.
 * Provides utilities for loading .glb files into Three.js scenes.
 */

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

export type ModelType = "suspect" | "room" | "evidence" | "furniture";

export interface TripoModel {
  id: string;
  name: string;
  type: ModelType;
  url: string; // Path to .glb file
  loaded: boolean;
  gltf?: any; // Loaded GLTF data
  scene?: THREE.Group;
  metadata?: {
    width?: number;
    height?: number;
    depth?: number;
    scale?: number;
    position?: [number, number, number];
    rotation?: [number, number, number];
  };
}

export class TripoModelManager {
  private static instance: TripoModelManager;
  private loader: GLTFLoader;
  private models: Map<string, TripoModel> = new Map();
  private cache: Map<string, any> = new Map(); // GLTF cache
  private loadingPromises: Map<string, Promise<any>> = new Map();

  private constructor() {
    this.loader = new GLTFLoader();
  }

  static getInstance(): TripoModelManager {
    if (!TripoModelManager.instance) {
      TripoModelManager.instance = new TripoModelManager();
    }
    return TripoModelManager.instance;
  }

  // ========== REGISTER MODEL ==========
  registerModel(model: TripoModel): void {
    this.models.set(model.id, model);
    console.log(`✅ Registered Tripo model: ${model.name} (${model.id})`);
  }

  // ========== LOAD MODEL ==========
  async loadModel(modelId: string): Promise<THREE.Group> {
    const model = this.models.get(modelId);
    if (!model) {
      throw new Error(`Model not found: ${modelId}`);
    }

    // Return cached model if already loaded
    if (model.loaded && model.scene) {
      console.log(`📦 Using cached model: ${model.name}`);
      return model.scene.clone();
    }

    // Check if already loading
    if (this.loadingPromises.has(modelId)) {
      return this.loadingPromises.get(modelId)!;
    }

    // Load from cache or file
    const loadPromise = this.loadModelFromFile(model);
    this.loadingPromises.set(modelId, loadPromise);

    try {
      const scene = await loadPromise;
      model.loaded = true;
      model.scene = scene;
      console.log(`✨ Loaded Tripo model: ${model.name}`);
      return scene.clone();
    } finally {
      this.loadingPromises.delete(modelId);
    }
  }

  // ========== LOAD FROM FILE ==========
  private async loadModelFromFile(model: TripoModel): Promise<THREE.Group> {
    // Check cache first
    if (this.cache.has(model.url)) {
      const cachedGLTF = this.cache.get(model.url);
      return cachedGLTF.scene.clone();
    }

    // Load from URL
    return new Promise((resolve, reject) => {
      this.loader.load(
        model.url,
        (gltf) => {
          // Cache the loaded data
          this.cache.set(model.url, gltf);
          model.gltf = gltf;

          // Calculate bounds and metadata
          const box = new THREE.Box3().setFromObject(gltf.scene);
          const size = box.getSize(new THREE.Vector3());

          model.metadata = {
            width: size.x,
            height: size.y,
            depth: size.z,
            scale: 1,
            position: [0, 0, 0],
            rotation: [0, 0, 0],
          };

          console.log(`📐 Model bounds:`, {
            width: size.x.toFixed(2),
            height: size.y.toFixed(2),
            depth: size.z.toFixed(2),
          });

          resolve(gltf.scene);
        },
        (progress) => {
          const percentComplete = (progress.loaded / progress.total) * 100;
          console.log(`⏳ Loading ${model.name}: ${percentComplete.toFixed(0)}%`);
        },
        (error) => {
          console.error(`❌ Error loading ${model.name}:`, error);
          reject(error);
        }
      );
    });
  }

  // ========== GET MODEL ==========
  getModel(modelId: string): TripoModel | undefined {
    return this.models.get(modelId);
  }

  // ========== LIST ALL MODELS ==========
  listModels(type?: ModelType): TripoModel[] {
    const models = Array.from(this.models.values());
    if (type) {
      return models.filter(m => m.type === type);
    }
    return models;
  }

  // ========== SCALE MODEL ==========
  scaleModel(scene: THREE.Group, factor: number): void {
    scene.scale.set(factor, factor, factor);
  }

  // ========== POSITION MODEL ==========
  positionModel(
    scene: THREE.Group,
    position: [number, number, number]
  ): void {
    scene.position.set(position[0], position[1], position[2]);
  }

  // ========== ROTATE MODEL ==========
  rotateModel(scene: THREE.Group, rotation: [number, number, number]): void {
    scene.rotation.set(rotation[0], rotation[1], rotation[2]);
  }

  // ========== FIT TO BOUNDS ==========
  fitModelToBounds(
    scene: THREE.Group,
    targetWidth: number,
    targetHeight?: number
  ): void {
    const box = new THREE.Box3().setFromObject(scene);
    const size = box.getSize(new THREE.Vector3());

    const scale = targetWidth / Math.max(size.x, size.y, size.z);
    this.scaleModel(scene, scale);

    // Re-center
    const newBox = new THREE.Box3().setFromObject(scene);
    const newSize = newBox.getSize(new THREE.Vector3());
    const newCenter = newBox.getCenter(new THREE.Vector3());

    scene.position.sub(newCenter);
  }

  // ========== CENTER MODEL ==========
  centerModel(scene: THREE.Group): void {
    const box = new THREE.Box3().setFromObject(scene);
    const center = box.getCenter(new THREE.Vector3());
    scene.position.sub(center);
  }

  // ========== GET BOUNDS ==========
  getModelBounds(scene: THREE.Group): {
    width: number;
    height: number;
    depth: number;
    center: THREE.Vector3;
  } {
    const box = new THREE.Box3().setFromObject(scene);
    const size = box.getSize(new THREE.Vector3());
    const center = box.getCenter(new THREE.Vector3());

    return {
      width: size.x,
      height: size.y,
      depth: size.z,
      center,
    };
  }

  // ========== CLEAR CACHE ==========
  clearCache(): void {
    this.cache.clear();
    this.models.forEach(model => {
      model.loaded = false;
      model.scene = undefined;
    });
    console.log("🗑️ Cleared model cache");
  }

  // ========== BATCH LOAD ==========
  async loadMultipleModels(modelIds: string[]): Promise<Map<string, THREE.Group>> {
    const results = new Map<string, THREE.Group>();

    const promises = modelIds.map(async (id) => {
      try {
        const scene = await this.loadModel(id);
        results.set(id, scene);
      } catch (error) {
        console.error(`Failed to load model ${id}:`, error);
      }
    });

    await Promise.all(promises);
    return results;
  }
}

// ========== PRESET CONFIGURATIONS ==========
export const MODEL_PRESETS = {
  SUSPECT_HEAD: {
    scale: 1,
    position: [0, 0, 0] as [number, number, number],
    rotation: [0, 0, 0] as [number, number, number],
  },
  ROOM_MODEL: {
    scale: 1,
    position: [0, 0, 0] as [number, number, number],
    rotation: [0, 0, 0] as [number, number, number],
  },
  EVIDENCE_ITEM: {
    scale: 0.1,
    position: [0, 1, 0] as [number, number, number],
    rotation: [0, 0, 0] as [number, number, number],
  },
};

export const applyPreset = (
  scene: THREE.Group,
  preset: typeof MODEL_PRESETS.SUSPECT_HEAD
): void => {
  const manager = TripoModelManager.getInstance();
  manager.scaleModel(scene, preset.scale);
  manager.positionModel(scene, preset.position);
  manager.rotateModel(scene, preset.rotation);
};

export default TripoModelManager.getInstance();
